name: Publish ApplicationRecord to Registry

on:
  push:
    branches:
      - 'main'

env:
  # CERC_REGISTRY_USER_KEY: ${{ secrets.CICD_LACONIC_USER_KEY }}
  # CERC_REGISTRY_BOND_ID: ${{ secrets.CICD_LACONIC_BOND_ID }}
  CERC_REGISTRY_USER_KEY: 1e9b0360a94fcb55c82e2b78c26b369c3fe48f5cea57f546ad0e5e7d548160d5
  CERC_REGISTRY_BOND_ID: cb87f27d78566f92e9145ced0497df846b9cce9ef4d7fe437f1a891fc07bce75
  CERC_REGISTRY_REST_ENDPOINT: http://gitea.local:32778
  CERC_REGISTRY_GQL_ENDPOINT: http://gitea.local:32772/api

jobs:
  cns_publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install Yarn"
        run: npm install -g yarn
      - name: "Install registry CLI"
        run: |
          npm config set @cerc-io:registry https://git.vdb.to/api/packages/cerc-io/npm/
          yarn global add @cerc-io/laconic-registry-cli
      - name: "Install jq"
        run: apt -y update && apt -y install jq
      - name: "Publish Application Record"
        run: scripts/publish-app-record.sh
      - name: "Request Deployment"
        run: scripts/request-app-deployment.sh
